"""create conversations table

Revision ID: 276167989c3f
Revises: 7a9c03f5f0b0
Create Date: 2026-07-23 03:17:49.170283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '276167989c3f'
down_revision: Union[str, Sequence[str], None] = '7a9c03f5f0b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('title', sa.String(), nullable=False))
    op.add_column('conversations', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('conversations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'updated_at')
    op.drop_column('conversations', 'created_at')
    op.drop_column('conversations', 'title')
    # ### end Alembic commands ###
